-- 회원 테이블
CREATE TABLE USERS(
    USER_NO NUMBER NOT NULL,
    ID VARCHAR2(32 BYTE) NOT NULL UNIQUE,
    PW VARCHAR2(64 BYTE) NOT NULL,  -- 암호화된 비번 최대 64바이트.
    NAME VARCHAR2(50 BYTE) NOT NULL,
    GENDER VARCHAR2(2 BYTE) NOT NULL,  -- M, F, NO
    EMAIL VARCHAR2(50 BYTE) NOT NULL UNIQUE,  -- 이메일 인증 때문에 UNIQUE
    MOBILE VARCHAR2(11 BYTE) NOT NULL,  -- 휴대전화번호(하이픈 제외 최대 11자리)
    BIRTHYEAR VARCHAR2(4 BYTE) NOT NULL,  -- 출생년도(YYYY)
    BIRTHDAY VARCHAR2(4 BYTE) NOT NULL,  -- 생일(MMDD)
    POSTCODE VARCHAR2(5 BYTE),  -- 우편번호
    ROAD_ADDRESS VARCHAR2(100 BYTE),  -- 도로명주소
    JIBUN_ADDRESS VARCHAR2(100 BYTE),  -- 지번주소
    DETAIL_ADDRESS VARCHAR2(100 BYTE),  -- 상세주소
    EXTRA_ADDRESS VARCHAR2(100 BYTE),  -- 참고항목
    POINT  NUMBER(10)   NOT NULL,    -- 포인트
    AGREE_CODE NUMBER NOT NULL,  -- 동의여부(0:필수, 1:필수+위치, 2:필수+프로모션, 3:필수+위치+프로모션)
    SNS_TYPE VARCHAR2(10 BYTE),  -- 간편가입종류(사이트가입:null, 네아로:naver)
    JOIN_DATE DATE NOT NULL,  -- 가입일
    PW_MODIFY_DATE DATE,    -- 비번 수정일
    INFO_MODIFY_DATE DATE,  -- 회원정보 수정일
    SESSION_ID VARCHAR2(32 BYTE),  -- 세션 아이디
    SESSION_LIMIT_DATE DATE  -- 세션 만료일
);


-- 접속기록 테이블
CREATE TABLE ACCESS_LOG(
    ACCESS_LOG_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL UNIQUE,
    LAST_LOGIN_DATE DATE NOT NULL
);

-- 탈퇴 테이블
CREATE TABLE RETIRE_USERS(
    USER_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL UNIQUE,
    JOIN_DATE DATE,  -- 가입일
    RETIRE_DATE DATE  -- 탈퇴일
);

-- 휴면 테이블
CREATE TABLE SLEEP_USERS(
    USER_NO NUMBER NOT NULL,
    ID VARCHAR2(45 BYTE) NOT NULL UNIQUE,
    PW VARCHAR2(64 BYTE) NOT NULL,  -- 암호화된 비번 최대 64바이트.
    NAME VARCHAR2(50 BYTE) NOT NULL,
    GENDER VARCHAR2(2 BYTE) NOT NULL,  -- M, F, NO
    EMAIL VARCHAR2(50 BYTE) NOT NULL UNIQUE,  -- 이메일 인증 때문에 UNIQUE
    MOBILE VARCHAR2(11 BYTE) NOT NULL,  -- 휴대전화번호(하이픈 제외 최대 11자리)
    BIRTHYEAR VARCHAR2(4 BYTE) NOT NULL,  -- 출생년도(YYYY)
    BIRTHDAY VARCHAR2(4 BYTE) NOT NULL,  -- 생일(MMDD)
    POSTCODE VARCHAR2(5 BYTE),  -- 우편번호
    ROAD_ADDRESS VARCHAR2(100 BYTE),  -- 도로명주소
    JIBUN_ADDRESS VARCHAR2(100 BYTE),  -- 지번주소
    DETAIL_ADDRESS VARCHAR2(100 BYTE),  -- 상세주소
    EXTRA_ADDRESS VARCHAR2(100 BYTE),  -- 참고항목
    AGREE_CODE NUMBER NOT NULL,  -- 동의여부(0:필수, 1:필수+위치, 2:필수+프로모션, 3:필수+위치+프로모션)
    SNS_TYPE VARCHAR2(10 BYTE),  -- 간편가입종류(사이트가입:null, 네아로:naver)
    JOIN_DATE DATE,  -- 가입일
    LAST_LOGIN_DATE DATE,  -- 마지막 로그인일
    SLEEP_DATE DATE  -- 휴면처리일
);
