


DROP TABLE SIGN;
DROP TABLE STUDENT;
DROP TABLE SUBJECT;


CREATE TABLE SUBJECT(
    SUB_CODE CHAR(1 BYTE) NOT NULL PRIMARY KEY,
    SUB_NAME VARCHAR2(4 BYTE) NOT NULL,
    SUB_PRO VARCHAR2(20 BYTE) NOT NULL
);
CREATE TABLE STUDENT(
    STU_CODE NUMBER(1) NOT NULL PRIMARY KEY,
    STU_NAME VARCHAR2(20 BYTE) NOT NULL,
    STU_AGE NUMBER(2) NOT NULL
);
CREATE TABLE SIGN(
    SIGN_NO NUMBER(1) NOT NULL,
    STU_CODE NUMBER(1) NOT NULL,
    SUB_CODE CHAR(1 BYTE) NOT NULL,
    CONSTRAINT PK_SIGN PRIMARY KEY(SIGN_NO),
    CONSTRAINT FK_SIGN_STUDENT FOREIGN KEY(STU_CODE) REFERENCES STUDENT(STU_CODE),
    CONSTRAINT FK_SIGN_SUBJECT FOREIGN KEY(SUB_CODE) REFERENCES SUBJECT(SUB_CODE)
       
);


    


