-- 테이블 스페이스
CREATE TABLESPACE TEMP_SPACE 
DATAFILE 'C:/temp/temp.dbf'
SIZE 1M;

-- 테이블 스페이스 삭제
DROP TABLESPACE TEMP_SPACE;   -- 1번쨰 방법
 
DROP TABLESPACE TEMP_SPACE    -- 2번째 방법 
 INCLUDING CONTENTS;
         
DROP TABLESPACE TEMP_SPACE          -- 3번째 방법
 INCLUDING CONTENTS AND DATAFILES;
 
 DROP TABLESPACE TEMP_SPACE
 INCLUDING CONTENTS AND DATAFILES   -- 4번째 방법(다없애는거)
       CASCADE CONSTRAINTS;
       
